title: project bayoen
# description: 프로젝트 바요엔 페이지; Page for project bayoen; プロジェクトばよえ~んのページ
description: Puyo Puyo Tetris Add-on
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
home_url: https://bayoen.github.io
star_url: https://bayoen.github.io/bayoen-star
lang_url: https://bayoen.github.io/star
latest_version: 0.1.0.3
