title: project bayoen
description: 프로젝트 바요엔 페이지; Page for project bayoen; プロジェクトばよえ~んのページ
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
home_url: https://bayoen.github.io
star_url: https://bayoen.github.io/bayoen-star